services:
  db:
    image: postgres:15
    container_name: spring_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: springdb
    ports:
      - "5432:5432"